name: Build and Package

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y sudo rsync

      - name: Create build user
        run: |
          sudo useradd -m builduser
          echo "builduser ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/builduser

      - name: Run build.sh as builduser
        run: |
          sudo cp -f config /home/builduser/config
          sudo chown -R builduser:builduser /home/builduser "$GITHUB_WORKSPACE"
          sudo -u builduser bash -c "
            cd '$GITHUB_WORKSPACE'
            bash build.sh
          "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-package
          path: /home/builduser/bin.tar.gz
